version: '2.2'

services:
  traefik:
    image: traefik:2.1
    restart: always
    command:
      - --docker
      - --docker.watch=true
      - --docker.exposedbydefault=false
    ports:
      - ${PORT:-80}:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_SECONDARY}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.middlewares.traefik-dashboard.redirectRegex.regex=/
      - traefik.http.middlewares.traefik-dashboard.redirectRegex.replacement=/dashboard/
    volumes:
      - ./configs/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
