version: '2.2'

services:
  traefik:
    image: traefik:1.7
    restart: always
    command:
      - --docker
      - --docker.watch=true
      - --docker.exposedbydefault=false
    ports:
      - ${PORT:-80}:80
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${DOMAIN_BACKEND}
    volumes:
      - ./configs/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
