[entryPoints]
  [entryPoints.http]
  address = ":80"

[providers]
  [providers.file]
  directory = "/etc/traefik"
  filename = "traefik.toml"

  [providers.docker]
  exposedByDefault = false

[api]
dashboard = true
