version: '2.2'

services:
  echo-server:
    image: viblo/echo-server:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=6001
      - traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/socket.io
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
      - AUTH_HOST=http://api:2015
      - AUTH_ENDPOINT=/broadcasting/auth
