version: '2.2'

services:
  mailhog:
    image: mailhog/mailhog
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog.rule=Host(`${DOMAIN_SECONDARY}`)
      - traefik.http.services.mailhog.loadbalancer.server.port=8025
    mem_limit: ${MEMORY_LIMIT_MAILHOG:-200m}
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/data
    volumes:
      - ${PATH_DATA:-./data}/mailhog:/data
