version: '2.2'

services:
  minio:
    image: minio/minio:latest
    restart: always
    command:
      - server
      - /data
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.${DOMAIN_SECONDARY}`)
      - traefik.http.services.minio.loadbalancer.server.port=9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio-secret}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME:-local}
    volumes:
      - ${PATH_DATA:-./data}/minio:/data
