version: '2.2'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${DOMAIN_BACKEND};PathPrefix:/pgadmin
    environment:
      - SCRIPT_NAME=/pgadmin
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin}       # Cannot be changed after first launch
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin} # Cannot be changed after first launch
    volumes:
      - ${PATH_DATA:-./data}/pgadmin:/var/lib/pgadmin               # Delete data files to start again with new user
