version: '2.2'

services:
  caddy:
    image: abiosoft/caddy:no-stats
    restart: always
    command:
      - root /php/${CADDY_ROOT:-public}
      - fastcgi / php:9000 php
      - |
        rewrite / {
          r .*
          to {path} {path}/ /index.php?{query}
        }
    labels:
      - traefik.enable=true
      - traefik.port=2015
      - traefik.frontend.rule=Host:${DOMAIN}
    volumes_from:
      - php

  php:
    image: sunasteriskrnd/php-workspace:7.4
    restart: always
    mem_limit: ${MEMORY_LIMIT_PHP_FPM:-1G}
    working_dir: /php
    volumes:
      - ${PATH_PHP}:/php
      - ${HOSTS_FILE}:/etc/hosts
