version: '2.2'

services:
  caddy:
    image: abiosoft/caddy:no-stats
    restart: always
    command:
      - root /php-fpm/${CADDY_ROOT:-public}
      - fastcgi / php-fpm:9000 php
      - |
        rewrite / {
          r .*
          to {path} {path}/ /index.php?{query}
        }
    labels:
      - traefik.enable=true
      - traefik.port=2015
      - traefik.frontend.rule=Host:${DOMAIN}
    volumes_from:
      - php-fpm

  php-fpm:
    image: viblo/php:fpm
    restart: always
    mem_limit: ${MEMORY_LIMIT_PHP_FPM:-1000m}
    working_dir: /php-fpm
    volumes:
      - ${PATH_PHP}:/php-fpm
      - ${HOSTS_FILE}:/etc/hosts
