version: '2.2'

services:
  caddy:
    image: abiosoft/caddy
    restart: always
    command:
      - "root /srv/public"
      - "log access.log"
      - "fastcgi / php-fpm:9000 php"
      - |
        rewrite / {
          r .*
          to /index.php?{query}
        }
    labels:
      - traefik.enable=true
      - traefik.port=2015
      - traefik.frontend.rule=Host:${DOMAIN} # This will be overriden in web.yml if it is enabled
    depends_on:
      - php-fpm

  php-fpm:
    image: viblo/php:fpm
    restart: always
    mem_limit: ${MEMORY_LIMIT_PHP_FPM:-1000m}
    working_dir: /srv
    volumes:
      - ${PATH_PHP}:/srv
