version: '2.2'

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    mem_limit: ${POSTGRES_MEMORY_LIMIT:-1000m}
    volumes:
      - ${PATH_DATA:-./data}/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  postgres-test:
    image: postgres:11-alpine
    restart: always
    mem_limit: ${POSTGRES_MEMORY_LIMIT:-1000m}
    volumes:
      - ${PATH_DATA:-./data}/postgres-test:/var/lib/postgresql/data
    ports:
      - ${DB_TEST_PORT:-5433}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
