version: '2.2'

services:
  web:
    image: node:10-alpine
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:${DOMAIN}
    working_dir: /srv
    volumes:
      - ${PATH_WEB}:/srv
      - ../sdk-js:/sdk-js
    expose:
      - 3000
    tty: true
    depends_on:
      - redis
    environment:
      - APP_KEY=${APP_KEY}
      - TZ=Asia/Ho_Chi_Minh
      - REDIS_HOST=redis

  api-proxy:
    image: viblo/api-proxy:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.web.frontend.rule=Host:${DOMAIN};PathPrefix:/api
    depends_on:
      - redis
    environment:
      - APP_KEY=${APP_KEY}
      - REDIS_HOST=redis
      - PROXY_TARGET=http://api-http:2015
      - PROXY_PREFIX=/api
      - PROXY_TARGET_NAME=VibloApi
