version: '2.2'

services:
  web:
    image: node:12-alpine
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:${DOMAIN}
    working_dir: /web
    volumes:
      - ${PATH_WEB}:/web
      - ${HOSTS_FILE}:/etc/hosts
    tty: true

  caddy:
    labels:
      - traefik.frontend.rule=Host:${DOMAIN};PathPrefixStrip:${API_PATH_PREFIX:-/api}
    networks:
      default:
        aliases:
          - api
