version: "2.2"

networks:
  default:
  frontend:
    external: true

services:
  web:
    image: node:12-alpine
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.rule=Host(`${DOMAIN}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-web.loadbalancer.server.port=3000
    networks:
      - default
      - frontend
    working_dir: /web
    volumes:
      - ${PATH_WEB}:/web
      - ${HOSTS_FILE}:/etc/hosts
    tty: true

  nginx:
    labels:
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-api-stripprefix.stripprefix.prefixes=${API_PATH_PREFIX:-/api}
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-api-stripprefix.stripprefix.forceSlash=false
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api-pathprefix.rule=Host(`${DOMAIN}`) && PathPrefix(`${API_PATH_PREFIX:-/api}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api-pathprefix.middlewares=${COMPOSE_PROJECT_NAME}-api-stripprefix@docker
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-api
